# Generated by Django 6.0.2 on 2026-06-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
