# Generated by Django 6.0.2 on 2026-06-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_notificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_hour', models.PositiveSmallIntegerField(default=10, help_text='UTC hour to send email notifications (0-23)')),
                ('max_posts_per_author', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
