# Generated by Django 6.0.2 on 2026-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_digestconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_emailed',
            field=models.BooleanField(default=False),
        ),
    ]
