# Generated by Django 6.0.2 on 2026-06-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='snapchat_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='sponsorship_url',
            field=models.URLField(blank=True),
        ),
    ]
