# Generated by Django 6.0.2 on 2026-06-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_snapchat_url_profile_sponsorship_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonus_donations',
            field=models.IntegerField(default=0),
        ),
    ]
