# Generated by Django 6.0.2 on 2026-06-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bonus_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bonus_donations',
        ),
    ]
